auth: # Enable the auth component
config: # Enables configuration UI
frontend: # Enables the frontend + themes
  themes: !include_dir_named themes/
hassio:
history: # en/disables support for showing history state changes over time
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 39
  unit_system: metric
  time_zone: Europe/Paris
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 172.30.33.0
  allowlist_external_dirs:
    - !secret hassio_dbpath
  packages: !include_dir_named packages/
  country: FR
http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-horizon-card/lovelace-horizon-card.js
      type: module
mobile_app:
recorder:
  purge_keep_days: 14
system_health:
automation: !include automations.yaml
sun:
energy:
my:
