recorder:
  include:
    entities:
      - input_select.home_activity

input_select:
  home_activity:
    options:
      - 'salon'
      - 'cuisine'
      - 'couloir'
      - 'switch_desktop'
      - 'dimmer_chambre'
      - 'dimmer_salon'

homeassistant:
  customize:
    input_select.home_activity:
      friendly_name: dernière activité
      icon: mdi:run-fast
