recorder:
  include:
    entities:
      - vacuum.cl4p_tp

homeassistant:
  customize:
    vacuum.cl4p_tp:
      icon: mdi:robot-vacuum-variant

automation:
  - id: notify_run_vaccum
    alias: notify asking to run vaccum
    trigger:
      platform: time
      at: '14:00:00'
    condition:
      - condition: state
        entity_id: vacuum.cl4p_tp
        state: 'docked'
      - condition: template
        value_template: '{{ not is_state(''person.manu'', ''home'')}}'
      - condition: template
        value_template: '{{ as_timestamp(utcnow()) - as_timestamp(state_attr(''vacuum.cl4p_tp'', ''clean_stop'')+''+00:00'') > 24*3600 }}'
    action:
      - service: notify.mobile_app_phone_manu
        data:
          title: 'faire le ménage ?'
          message: >
            dernier ménage il y a {{ ((as_timestamp(now()) - as_timestamp(state_attr('vacuum.cl4p_tp', 'clean_stop')) | int) / 3600 / 24) | round(0) }} jour(s) et {{ ((as_timestamp(now()) - as_timestamp(state_attr('vacuum.cl4p_tp', 'clean_stop')) | int) / 3600 % 24) | round(0) }} heure(s)
          data:
            icon: /local/notification/vacuum-off.png
            url: !secret endpoint_bedroom
            tag: 'cl4p-tp'
            actions:
            - title: nettoyer
              action: vacuum_clean
  - id: notify_run_vaccum_days
    alias: notify asking to run vaccum after days
    trigger:
      platform: time
      at: '14:00:00'
    condition:
      - condition: state
        entity_id: vacuum.cl4p_tp
        state: 'docked'
      - condition: template
        value_template: '{{ as_timestamp(utcnow()) - as_timestamp(state_attr(''vacuum.cl4p_tp'', ''clean_stop'')+''+00:00'') > 5*24*3600 }}'
    action:
      - service: notify.mobile_app_phone_manu
        data:
          title: 'faire le ménage ?'
          message: >
            dernier ménage il y a {{ ((as_timestamp(now()) - as_timestamp(state_attr('vacuum.cl4p_tp', 'clean_stop')) | int) / 3600 / 24) | round(0) }} jour(s) et {{ ((as_timestamp(now()) - as_timestamp(state_attr('vacuum.cl4p_tp', 'clean_stop')) | int) / 3600 % 24) | round(0) }} heure(s)
          data:
            icon: /local/notification/vacuum-off.png
            url: !secret endpoint_bedroom
            tag: 'cl4p-tp'
            actions:
            - title: nettoyer
              action: vacuum_clean

  - id: vacuum_running
    alias: vaccum is running
    trigger:
      platform: state
      entity_id: vacuum.cl4p_tp
      to: 'cleaning'
    action:
      - service: notify.mobile_app_phone_manu
        data:
          message: 'ménage en cours'
          data:
            icon: /local/notification/vacuum-on.png
            url: !secret endpoint_bedroom
            tag: 'cl4p-tp'
            actions:
            - title: arrêter
              action: vacuum_stop
            - title: docker
              action: vacuum_dock

  - id: vacuum_running_done
    alias: vaccum is done
    trigger:
      platform: state
      entity_id: vacuum.cl4p_tp
      from: 'cleaning'
    condition:
      - condition: template
        value_template:  '{{ trigger.from_state.state != ''unknown'' }}'
    action:
      - service: notify.mobile_app_phone_manu
        data:
          title: 'cl4p-tp a fini son ménage: {{ states(''vacuum.cl4p_tp'') }}'
          # message: >
          #   {% if is_state('light.all', 'on') %}
          #     lumières allumées
          #   {% else %}
          #     lumières éteintes
          #   {% endif %}
          data:
            icon: /local/notification/vacuum-done.png
            url: !secret endpoint_bedroom
            tag: 'cl4p-tp'
            actions:
            - title: nettoyer
              action: vacuum_clean
            # - title: éteindre lumières
            #   action: all_lights_off
