recorder:
  include:
    entities:
      - sensor.france_coronavirus_confirmed
      - sensor.france_coronavirus_current
      - sensor.france_coronavirus_recovered
      - sensor.france_coronavirus_deaths
      - sensor.germany_coronavirus_confirmed
      - sensor.germany_coronavirus_current
      - sensor.germany_coronavirus_recovered
      - sensor.germany_coronavirus_deaths
      - sensor.austria_coronavirus_confirmed
      - sensor.austria_coronavirus_current
      - sensor.austria_coronavirus_recovered
      - sensor.austria_coronavirus_deaths

homeassistant:
  customize:
    sensor.france_coronavirus_confirmed:
      friendly_name: confirmés
      icon: mdi:emoticon-neutral-outline
    sensor.france_coronavirus_current:
      friendly_name: en cours
      icon: mdi:emoticon-sad-outline
    sensor.france_coronavirus_recovered:
      friendly_name: rétablis
      icon: mdi:emoticon-outline
    sensor.france_coronavirus_deaths:
      friendly_name: morts
      icon: mdi:emoticon-dead-outline

    sensor.germany_coronavirus_confirmed:
      friendly_name: confirmés
      icon: mdi:emoticon-neutral-outline
    sensor.germany_coronavirus_current:
      friendly_name: en cours
      icon: mdi:emoticon-sad-outline
    sensor.germany_coronavirus_recovered:
      friendly_name: rétablis
      icon: mdi:emoticon-outline
    sensor.germany_coronavirus_deaths:
      friendly_name: morts
      icon: mdi:emoticon-dead-outline

    sensor.austria_coronavirus_confirmed:
      friendly_name: confirmés
      icon: mdi:emoticon-neutral-outline
    sensor.austria_coronavirus_current:
      friendly_name: en cours
      icon: mdi:emoticon-sad-outline
    sensor.austria_coronavirus_recovered:
      friendly_name: rétablis
      icon: mdi:emoticon-outline
    sensor.austria_coronavirus_deaths:
      friendly_name: morts
      icon: mdi:emoticon-dead-outline

