media_player:
  - platform: universal
    name: cuisine_universal
    children:
      - media_player.cuisine
      - media_player.appartement
    state_template: >
      {% if is_state('media_player.cuisine', 'off') and is_state('media_player.appartement', 'off') %}
        off
      {% elif is_state('media_player.cuisine', 'off') %}
        {{ states('media_player.appartement') }}
      {% else %}
        {{ states('media_player.cuisine') }}
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.cuisine
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.cuisine

homeassistant:
  customize:
    media_player.cuisine:
      icon: mdi:speaker

    media_player.cuisine_universal:
      icon: mdi:cast-audio
      friendly_name: cuisine
