enocean:
  device: !secret enocean_usb_path

binary_sensor:
  - platform: enocean
    id: !secret enocean_desktop_switch_id
    name: desktop

automation:
  # desktop switch : toggle light / pc
  - id: desktop_switch_ecran
    alias: desktop switch - ecran
    trigger:
      platform: event
      event_type: button_pressed
      event_data:
        id: !secret enocean_desktop_switch_id
        pushed: 0
        which: 1
        onoff: 0
    action:
      - service: switch.toggle
        data:
          entity_id: switch.ecran
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_activity
          option: switch_desktop

  - id: desktop_switch_pc
    alias: desktop switch - pc
    trigger:
      platform: event
      event_type: button_pressed
      event_data:
        id: !secret enocean_desktop_switch_id
        pushed: 0
        which: 1
        onoff: 1
    action:
      - service: switch.toggle
        data:
          entity_id: switch.pc_switch_safe
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_activity
          option: switch_desktop
