sensor:
  - platform: google_wifi
    host: !secret ip_google_wifi

homeassistant:
  customize:
    sensor.google_wifi_status:
      friendly_name: état
      icon: mdi:checkbox-marked-circle-outline

    sensor.google_wifi_current_version:
      friendly_name: version
      icon: mdi:alert-decagram

    sensor.google_wifi_new_version:
      friendly_name: mise à jour

    sensor.google_wifi_local_ip:
      friendly_name: google wifi (ip)
      icon: mdi:ip-network-outline

    sensor.google_wifi_uptime:
      friendly_name: uptime wifi
      icon: mdi:access-point-network
