automation:
  # clic sur 'éteindre le pc'
  - id: app_turn_off_pc_notif
    alias: (app) turn off pc from notification
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: pc_switch_safe_off
    action:
      - service: switch.turn_off
        entity_id: switch.pc_switch_safe

  #clic sur 'désactiver 30min' (intrusion_check)
  - id: app_intrusion_check_disable
    alias: (app) disable intrusion_check automation for 30 min
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: intrusion_check_disable
    action:
      - service: automation.turn_off
        entity_id: automation.intrusion_check
      - delay: 00:30:00
      - service: automation.turn_on
        entity_id: automation.intrusion_check
