switch:
  - platform: template
    switches:
      pc_universal:
        value_template: "is_state('switch.pc_switch_safe', 'on')"
        turn_on:
          action: switch.turn_on
          data:
            entity_id: switch.pc_switch_safe
        turn_off:
          action: switch.turn_off
          data:
            entity_id: switch.pc_switch_safe

homeassistant:
  customize:
    switch.pc_universal:
      icon: mdi:desktop-tower
      friendly_name: pc

script:
  pc_turn_off:
    alias: pc turn off (dependency)
    sequence:
      - action: switch.turn_off
        entity_id: switch.pc_switch
      - wait_template: "{{ float(states('sensor.ecran_power')) < 6 }}"
        timeout:
          minutes: 1
        continue_on_timeout: false
      - action: switch.turn_off
        entity_id: switch.ecran
