recorder:
  include:
    entities:
      - person.manu

person:
  - name: manu
    id: manu
    device_trackers:
      - device_tracker.manu_wifi
      - device_tracker.manu_phone

binary_sensor:
  - platform: template
    sensors:
      manu:
        device_class: occupancy
        value_template: >
          {{ is_state('person.manu', 'home') }}

homeassistant:
  customize:
    device_tracker.google_maps_102756001364712049780:
      friendly_name: manu
      icon: mdi:google-maps

    device_tracker.manu_wifi:
      icon: mdi:cellphone-wireless
      friendly_name: pixel 5 (wifi)

    device_tracker.manu_phone:
      icon: mdi:cellphone
      friendly_name: pixel 5

    person.manu:
      icon: mdi:human-male
