recorder:
  include:
    entities:
      - person.manu

person:
  - name: manu
    id: manu
    device_trackers:
      - device_tracker.manu_wifi
      - device_tracker.manu_phone

template:
  - binary_sensor:
      - device_class: occupancy
        default_entity_id: binary_sensor.manu
        state: "{{ is_state('person.manu', 'home') }}"
        name: manu

homeassistant:
  customize:
    device_tracker.google_maps_102756001364712049780:
      friendly_name: manu
      icon: mdi:google-maps

    device_tracker.manu_wifi:
      icon: mdi:cellphone-wireless
      friendly_name: pixel 9 pro (wifi)

    device_tracker.manu_phone:
      icon: mdi:cellphone
      friendly_name: pixel 9 pro

    person.manu:
      icon: mdi:human-male
