media_player:
  - platform: universal
    name: gobelin_universal
    children:
      - media_player.gobelin
      - media_player.appartement
    state_template: >
      {% if is_state('media_player.gobelin', 'off') and is_state('media_player.appartement', 'off') %}
        off
      {% elif is_state('media_player.gobelin', 'off') %}
        {{ states('media_player.appartement') }}
      {% else %}
        {{ states('media_player.gobelin') }}
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.gobelin
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.gobelin

homeassistant:
  customize:
    media_player.gobelin_universal:
      icon: mdi:cast-audio
      friendly_name: gobelin
