media_player:
  - platform: universal
    name: salon_universal
    children:
      - media_player.salon
      - media_player.appartement
    state_template: >
      {% if is_state('media_player.salon', 'off') and is_state('media_player.appartement', 'off') %}
        off
      {% elif is_state('media_player.salon', 'off') %}
        {{ states('media_player.appartement') }}
      {% else %}
        {{ states('media_player.salon') }}
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.salon
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.salon

homeassistant:
  customize:
    media_player.salon:
      icon: mdi:speaker

    media_player.salon_universal:
      icon: mdi:speaker-wireless
      friendly_name: salon
