homeassistant:
  customize:
    media_player.shield_universal:
      icon: mdi:youtube-tv
      friendly_name: shield

    media_player.shield_cast:
      icon: mdi:cast

    media_player.shield_tv:
      icon: mdi:youtube-tv

media_player:
  - platform: universal
    name: shield_universal
    children:
      - media_player.shield_cast
      - media_player.shield_tv
      - media_player.beam
    state_template: >
      {% if has_value('sensor.tv_power') and is_state('media_player.shield_tv','off') and is_state('media_player.shield_cast','off') and states('sensor.tv_power') | float | round(1) < 0.4 %}
        off
      {% elif has_value('sensor.tv_power') and states('sensor.tv_power') | float | round(1) < 0.4 %}
        tv off
      {% else %}
        {{ states('media_player.shield_tv') }}
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.shield_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.shield_tv
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.beam
          volume_level: '{{ volume_level }}'
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.beam
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.beam
      volume_mute:
        service: media_player.volume_mute
        data_template:
          entity_id: media_player.beam
          is_volume_muted: '{{ is_volume_muted }}'
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.shield_tv
          source: '{{ source }}'
    attributes:
      is_volume_muted: media_player.beam|is_volume_muted
      volume_level: media_player.beam|volume_level
      source: media_player.shield_tv|source
      source_list: media_player.shield_tv|source_list
