recorder:
  include:
    entities:
      - sensor.mogaba_used_space_volume_1
      - sensor.mogaba_volume_used_volume_1

homeassistant:
  customize:
    sensor.mogaba_volume_used_volume_1:
      friendly_name: stockage utilisé

    sensor.mogaba_total_size_volume_1:
      icon: mdi:harddisk
