homeassistant:
  customize:
    script.tv_input_android_tv:
      friendly_name: input android tv
      icon: mdi:youtube-tv

    script.tv_input_console:
      friendly_name: input console
      icon: mdi:sony-playstation

    script.tv_input_side:
      friendly_name: input hdmi side
      icon: mdi:video-input-hdmi

script:
  tv_input_android_tv:
    alias: tv sur android tv (hdmi 2)
    sequence:
    - condition: numeric_state
      entity_id: sensor.tv_power
      above: 0.4
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: !secret harmony_tv_id
        command: InputHdmi2

  tv_input_console:
    alias: tv sur console (hdmi 3)
    sequence:
    - condition: numeric_state
      entity_id: sensor.tv_power
      above: 0.4
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: !secret harmony_tv_id
        command: InputHdmi3

  tv_input_side:
    alias: tv sur hdmi side
    sequence:
    - condition: numeric_state
      entity_id: sensor.tv_power
      above: 0.4
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: !secret harmony_tv_id
        command: InputHdmiSide
