recorder:
  include:
    entities:
      - sensor.current_version
      - sensor.release_version

sensor:
  - platform: rest
    resource: !secret endpoint_release
    name: release_version
    value_template: '{{ value_json.homeassistant.yellow }}'

command_line:
  - sensor:
      command: 'curl http://supervisor/supervisor/available_updates -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"updates": [.data.available_updates[] | .update_type]}'''
      name: updater
      scan_interval: 600
      value_template: "{{ value_json.updates | length }}"
      json_attributes:
        - updates
      unit_of_measurement: updates

homeassistant:
  customize:
    sensor.current_version:
      friendly_name: version installée
      icon: mdi:raspberry-pi

    sensor.release_version:
      friendly_name: version disponible
      icon: mdi:cloud-download

    sensor.updater:
      friendly_name: update(s) available
      icon: mdi:download

automation:
  # available updates
  - id: update_available
    alias: update available
    trigger:
      platform: state
      entity_id: sensor.updater
    condition:
      - condition: numeric_state
        entity_id: sensor.updater
        above: 0
    action:
      - service: notify.mobile_app_phone_manu
        data:
          message: '{{ states(''sensor.updater'') }} pending update(s) available'
          data:
            icon: /local/notification/cloud-download.png
            clickAction: !secret endpoint_config
            tag: 'update'
