recorder:
  include:
    entities:
      - sensor.meteo_france_temperature

template:
  - sensor:
      - unit_of_measurement: °C
        default_entity_id: sensor.meteo_france_temperature
        state: "{{ state_attr('weather.lilas', 'temperature') }}"
        name: meteo_france_temperature

homeassistant:
  customize:
    weather.lilas:
      friendly_name: météo (météo france)

    weather.tomorrow_io_home_daily:
      friendly_name: météo (tomorrow.io)

    sensor.lilas_cloud_cover:
      friendly_name: nuages
      icon: mdi:clouds

    sensor.lilas_daily_precipitation:
      friendly_name: précipitations
      icon: mdi:weather-pouring

    sensor.lilas_rain_chance:
      friendly_name: pluie

    sensor.lilas_snow_chance:
      friendly_name: neige
      icon: mdi:weather-snowy-heavy

    sensor.lilas_freeze_chance:
      friendly_name: gel
      icon: mdi:snowflake-thermometer

    sensor.meteo_france_temperature:
      friendly_name: température (météo france)
