recorder:
  include:
    entities:
      - sensor.meteo_france_temperature

sensor:
  - platform: template
    sensors:
      meteo_france_temperature:
        value_template: >
          {{ state_attr('weather.lilas', 'temperature') }}
        unit_of_measurement: °C

homeassistant:
  customize:
    weather.lilas:
      friendly_name: météo (météo france)

    weather.tomorrow_io_home_daily:
      friendly_name: météo (tomorrow.io)

    sensor.lilas_cloud_cover:
      friendly_name: nuages

    sensor.lilas_daily_precipitation:
      friendly_name: précipitations
  
    sensor.lilas_rain_chance:
      friendly_name: pluie

    sensor.lilas_snow_chance:
      friendly_name: neige

    sensor.lilas_freeze_chance:
      friendly_name: gel
      icon: mdi:snowflake-alert

    sensor.meteo_france_temperature:
      friendly_name: température (météo france)
